### ISSUE TITLE
ERROR: ycmd--on-unparsed-buffer-focus

### ISSUE THREAD

**Issue by curbina** [abingham/spacemacs-layers#4]
Error running timer `ycmd--on-unparsed-buffer-focus': (error "ERROR: Ycmd server timeout")

MBPr 2.3 GHz Intel Core i7, 16GB, NVIDIA GeForce GT 750M 2048 MB
OS X Yosemite v. 10.10.5
Developer Tools: Xcode: 7.2.1 (9548.1)

Emacs v. 24.5 (9.0)
spacemacs-layers w/ ycmd and emacs-ycmd

Spacemacs will run sometimes, but most of the time I keep getting the error message shown above.

Regards,
Tomas

**Comment by abingham** [comment]
This repository is really just my personal spacemacs config. You're of course free to use it, but I'm not going to put any effort into fixing problems other people have with it. Sorry :(

**Comment by curbina** [comment]
No, problem.
